version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_dev
    ports:
      - "3306:3306"

  app:
    image: library-management-system:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_dev
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - app-logs:/app/logs
    depends_on:
      - db

volumes:
  app-logs:

# docker stack deploy -c docker-compose.yml library-management-system
# docker stack rm library-management-system
